### ISSUE TITLE
Setting init-expanded to true from html is not working

### ISSUE THREAD

**Issue by IshankKulshrestha** [heidji/ionic4-hidenav#1]
<hidenav-stretchheader [hidenav-rel-content]="content">
    <div #shrinkexpand header-height="45" init-expanded="true" opacity-factor="8" opacity-color="#37686e">
        </div>
</div>

Setting init-expanded to true from html is not working.

**Comment by heidji** [comment]
could you please update the version to 0.0.4 and test again? i had forgotten to add this feature to the npm package but now it should be there..

**Comment by IshankKulshrestha** [comment]
Updated the package but still the same result.
+ ionic4-hidenav@0.0.4
added 1 package in 3.487s

**Comment by heidji** [comment]
could you please show me your html + css, i tested the package on my project and it worked so i can't know why it isn't working for you..

**Comment by heidji** [comment]
issue fixed
