### ISSUE TITLE
Add support for iPhone X, XR, XS and XSMax

### ISSUE THREAD

**Issue by iCodr8** [heidji/ionic4-hidenav#3]
On iPhone X the header is moved in the safe area. This should be fixed with this:

```
var(--ion-safe-area-top, 0)
```

**Comment by heidji** [comment]
hey, isn't it possible to add it yourself? at least ionic 3 also don't include this out of the box afaik ..

**Comment by iCodr8** [comment]
I can not implement it myself, because `[header-height]="44 + safeAreaTop"` can not be used.
Ionic 4 implements the safe area for iPhone X etc.

**Comment by heidji** [comment]
seems correct. could you please help out with a pull request? I have currently too much on my hands on other things..

**Comment by ludufre** [comment]
It would be very useful

**Comment by tebantebanteban** [comment]
Hi!  i've Solved using

hidenav-stretchheader { 
    padding-top:env(safe-area-inset-top);
}

**Comment by heidji** [comment]
thanks, i will test it and include it

**Comment by heidji** [comment]
I did add the variable, tho I do think it's a bit wonky.

**Comment by tebantebanteban** [comment]
Hi! I think I found a solution
first, declare on global.scss 

```
:root {
    --sat: env(safe-area-inset-top);
    --sar: env(safe-area-inset-right);
    --sab: env(safe-area-inset-bottom);
    --sal: env(safe-area-inset-left);
}
```
Next, in 
in node_modules/ionic4-hidenav/fesm2015/ionic4-hidenav.js
replace

`this.data[name].shrinkexpandheaderHeight = parseInt(parentElem.getAttribute('header-height'), 10);
`

for

```
var notchHeight = parseInt(getComputedStyle(document.documentElement).getPropertyValue("--sat"), 10);
var newHeight = parseInt(parentElem.getAttribute('header-height'), 10)+notchHeight;
this.data[name].shrinkexpandheaderHeight = newHeight;
```

works perfect!, just set header-height without notch and works fine with any device!

**Comment by heidji** [comment]
sounds really nice, could you do a PR?

**Comment by heidji** [comment]
i made a slight modification to your proposal and seems to be working! thanks for your help!
will be pushing a new version when I fix the other issues

**Comment by heidji** [comment]
@tebantebanteban the new version 0.1.7 is out since yesterday

**Comment by tebantebanteban** [comment]
> @tebantebanteban the new version 0.1.7 is out since yesterday

Thanks !!!

**Comment by mik-bcmllp** [comment]
Doesn't seem to be working for me. I'm having to add 30px padding via CSS to fix the issue on phones with a notch.
Is anyone else seeing this problem?
