### ISSUE TITLE
Overlay layer Flickering on fast scrolling

### ISSUE THREAD

**Issue by tebantebanteban** [heidji/ionic4-hidenav#5]
Hi!, Overlay flickering on fast scrolling. Overlay layer shows with full opacity when scroll down fast

Solved replacing

```
overlay.style.setProperty('--opacity', this.data[name].opacityFactor / 10 * Math.min(e.detail.scrollTop / (this.data[name].shrinkexpandHeight / 2), 1));
```

for 
```
if(this.data[name].opacityFactor / 10 * Math.min(e.detail.scrollTop / (this.data[name].shrinkexpandHeight / 2), 1) > 0){
                        
overlay.style.setProperty('--opacity', this.data[name].opacityFactor / 10 * Math.min(e.detail.scrollTop / (this.data[name].shrinkexpandHeight / 2), 1));
                    
}
```

in ionic4-hidenav.js

**Comment by heidji** [comment]
thanks, will include and update

**Comment by tebantebanteban** [comment]
On next release please change >0 for >= 0 and works perfect!  

Thanks!!

**Comment by tebantebanteban** [comment]
on new version need to replace
`overlay.style.setProperty('--opacity', newValOpacity);`

for 


```
if (this.data[name].opacityFactor / 10 * Math.min(e.detail.scrollTop / (this.data[name].shrinkexpandHeight / 2), 1) > 0) {

                                        overlay.style.setProperty('--opacity', newValOpacity);

                                    }
```

**Comment by heidji** [comment]
This code actually didn't work very well so I had to tweak it with something like: if the new calculated value is different than the current one then => verlay.style.setProperty('--opacity', newValOpacity); otherwise do nothing, which should result in something similar to what you need, but only it works better

**Comment by tebantebanteban** [comment]
With actual version

![ezgif-2-5cbba0aeac23](https://user-images.githubusercontent.com/31634150/73471875-d5bfd480-4368-11ea-9106-a02c67eca0fe.gif)


Maybe the restriction was a bit difficult, but adding this, it works fine

```
if (currentValOpacity != newValOpacity){
                                    if (e.detail.scrollTop > 0) {

                                        overlay.style.setProperty('--opacity', newValOpacity);

                                    }
                                }
```

The result would be this


![ezgif-2-dbd6fdf75b3f](https://user-images.githubusercontent.com/31634150/73472760-503d2400-436a-11ea-825f-4cbf596f5be2.gif)


Now, as a query, can you make the scroll grow, the header grows? and that when released it returns to its position? something like an elastic Header ?, I have looked for what part to modify to achieve this effect but I have not been able to find it

**Comment by heidji** [comment]
ok I think i misunderstood the problem, i will try to add something to eliminate this behavior

**Comment by heidji** [comment]
could you check if 0.1.9 fixes your problem pls?

**Comment by tebantebanteban** [comment]
> could you check if 0.1.9 fixes your problem pls?

Sorry!! Works perfect! Can you unlock header for increment size when scroll?
