### ISSUE TITLE
Implement Moving Title and Back Button

### ISSUE THREAD

**Issue by xxpolox** [heidji/ionic4-hidenav#7]
Hi,

Good Job @heidji.
Please, can you tell me how can i implement the "moving title", what is the structure in the #shrinkexpand Div.
I would like to implement it like the example gif (cat`s image) when you scroll up and the image shrinked with the text: "moving Title".

In the other hand, where may put <ion-back-button>?

Please your help.
Sorry for my english.

**Comment by heidji** [comment]
Hey, thanks!
there's an example project which includes the moving title, [check it out](https://github.com/heidji/ionic4-hidenav-example)

Good luck!

**Comment by xxpolox** [comment]
Oh, i didn't see that!, LOL
Thanks my friend!
