### ISSUE TITLE
Moving Title appears in Top position even when Image is Exanded

### ISSUE THREAD

**Issue by xxpolox** [heidji/ionic4-hidenav#8]
Hi my friend,

Please can you tell me how can i set the position of "Moving Title" in the bottom of the hidenav (in expanded position), by default.
The "moving title" works fine when the hidenav is setted "init-expanded="false", but when i set "init-expanded="true", the "moving title" begin in top of the page and then when i scroll up, the "moving Title" disappears of the Top and appears in the bottom and start to moving up.

Thanks for your help.

**Comment by xxpolox** [comment]
I`m trying to get the height of the hidenav with: this.hidenav.headerHeight, for set the "translate3d" before the page scrolling, but console log show: undefined.

:/

**Comment by heidji** [comment]
hey, in this case you need to set the initial title position manually. you will probably not get the height before the header is initialized, so either way i recommend you set it to a fixed empirical value.
